### PR TITLE
Updated javascript syntax

### PR DESCRIPTION
**Pull request by dalton-f**
Made some small changes to update the syntax to ES6

### CODE REVIEW

**Comment by Arisamiga** [comment]
Hello @NexusOblivion! Thanks so much for contributing :D

There seems to be a problem with the Sleep function that was edited (Can you check if you forgot any "{") ?

**Comment by dalton-f** [comment]
Hi @Arisamiga. Will take a lot now and update the request - I may also take a look at fully refactoring the main checkWin() function soon

**Comment by dalton-f** [comment]
Looks like it should be working now - let me know! (tested with 2000ms and getting a longer delay)

**Comment by Arisamiga** [comment]
> Looks like it should be working now - let me know! (tested with 2000ms and getting a longer delay)

Checked and everything works! I will merge this now. Thanks so much for contributing :D

**Pull request merged**
