### PR TITLE
Added helper functions

### PR DESCRIPTION
**Pull request by dalton-f**
Added a handful of helper functions to help with the readability and robustness of code + also helpful for future contributions and saves a few keystrokes especially for the repeated document.getElementById

### CODE REVIEW

**Comment by dalton-f** [comment]
Any updates on this @Arisamiga? Thanks!

**Review by Arisamiga — CHANGES_REQUESTED** [review]
Hello @dalton-f Sorry for the late response.

Everything looks great! What I want to suggest is that instead of having "getById" and "getByClassName" have "getElementById" and "getElementByClassName" for it to be clearer.

**Comment by dalton-f** [comment]
Hey @Arisamiga 

I can certainly make that happen, getById is just habit for me from other code I've worked with. 

I will make these changes and also add one for .innerText and (anything else I find suitable) and update the pull request tomorrow 

I can also expand upon getById to have it not just limited to document but allow for any selector, if you think that'd be helpful

**Comment by Arisamiga** [comment]
> Hey @Arisamiga
> 
> I can certainly make that happen, getById is just habit for me from other code I've worked with.
>
> I will make these changes and also add one for .innerText and (anything else I find suitable) and update the pull request tomorrow

Yeah! That would be a good idea!

> I can also expand upon getById to have it not just limited to document but allow for any selector, if you think that'd be helpful

Not sure if that is needed at the moment as we are not using a different selector.

**Comment by dalton-f** [comment]
> > Hey @Arisamiga
> > 
> > I can certainly make that happen, getById is just habit for me from other code I've worked with.
> >
> > I will make these changes and also add one for .innerText and (anything else I find suitable) and update the pull request tomorrow
> 
> Yeah! That would be a good idea!
> 

Will have it committed tommorow!

> > I can also expand upon getById to have it not just limited to document but allow for any selector, if you think that'd be helpful
> 
> Not sure if that is needed at the moment as we are not using a different selector.

Understandable, there's always room to expand on the functions if it's needed

**Comment by dalton-f** [comment]
@Arisamiga updated the helper function names, will add .innerText in a separate pull request when I get the chance to refactor the rest of the code :)

**Review by Arisamiga — APPROVED** [review]
Everything Looks good! Feel free to create another Pull Request for the .innerText. I will merge these changes now

Thanks so much for contributing :D

**Pull request merged**
